---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  
  collections:
    - f5networks.f5_modules
 
  tasks:
    - name: Setup provider
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          server_port: "443"
          validate_certs: false
    - name: Download a new UCS
      bigip_ucs_fetch:
        src: "{{ ucs }}"
        dest: "{{ '/tmp/ucs/' + ucs }}"
        #only_create_file: true
        provider: "{{ provider }}"
      delegate_to: localhost

