---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  collections:
    - f5networks.f5_modules
    
  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{private_ip}}"
        server_port: "443"
        validate_certs: "False"

    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{ansible_host}}"
        server_port: "{{server_port}}"
        validate_certs: "False"
      when: server_port is defined

    - name: ADD VIRTUAL SERVER
      bigip_virtual_server:
        provider: "{{provider}}"
        name: "{{vip}}"
        destination: "{{vip_ip}}"
        port: "80"
        enabled_vlans: "all"
        #all_profiles: ['http','clientssl','oneconnect']
        all_profiles: ['http']
        pool: "http_pool"
        snat: "Automap"

    - name: PRINT OUT WEB VIP FOR F5
      debug:
        msg: "The VIP (Virtual IP) is http://{{vip_ip}}"
