---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  collections:
    - f5networks.f5_modules
    
  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{private_ip}}"
        server_port: "443"
        validate_certs: "False"

    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{ansible_host}}"
        server_port: "{{server_port}}"
        validate_certs: "False"
      when: server_port is defined

    - name: CREATE NODES
      bigip_node:
        provider: "{{provider}}"
        host: "1.1.1.1"
        name: "1.1.1.1"
      loop: "{{ groups['web'] }}"

  
